# Generated by Django 5.0.7 on 2025-02-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_blogscategories_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
