# Generated by Django 5.0.7 on 2025-03-01 22:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_bookings_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="therapist_description",
            field=ckeditor.fields.RichTextField(default="null"),
            preserve_default=False,
        ),
    ]
