# Generated by Django 5.0.7 on 2025-03-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_user_therapist_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogscategories",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
