# Generated by Django 5.0.7 on 2025-03-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_blogscategories_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("desc", models.CharField(max_length=1000)),
                ("sub_desc", models.CharField(max_length=1000)),
                ("caution", models.CharField(max_length=1000)),
                ("scoring_name", models.CharField(max_length=100)),
                ("leveling_name", models.CharField(max_length=100)),
                ("calculation_para", models.TextField()),
                ("result_line", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CalculatorResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min", models.IntegerField()),
                ("max", models.IntegerField()),
                ("result", models.CharField(max_length=200)),
                (
                    "calculator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculator_results",
                        to="api.calculators",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalculatorQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                (
                    "calculator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculator_questions",
                        to="api.calculators",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CalculatorScores",
        ),
    ]
