# Generated by Django 5.0.7 on 2025-03-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_calculatorscores"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculators",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="calculators/"),
        ),
    ]
