# Generated by Django 5.0.7 on 2025-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_calculators_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculatorquestions",
            name="option1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="calculatorquestions",
            name="option2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="calculatorquestions",
            name="option3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="calculatorquestions",
            name="option4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
