# Generated by Django 5.0.7 on 2025-03-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_calculatorquestions_option1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculatorquestions",
            name="question",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
