# Generated by Django 5.0.7 on 2025-03-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_calculatorquestions_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculatorresults",
            name="max",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
