# Generated by Django 5.0.7 on 2025-03-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_calculatorresults_max"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookings",
            name="payment_method",
            field=models.CharField(
                choices=[("online", "Online"), ("physical", "Physical")],
                default="physical",
                max_length=10,
            ),
        ),
    ]
