# Generated by Django 5.0.7 on 2025-03-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_bookings_paid_bookings_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="receipt",
            field=models.ImageField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
